cleanup default next app folder structure

diff --git a/frontend/next-app/Dockerfile b/frontend/next-app/Dockerfile
--- a/frontend/next-app/Dockerfile
+++ b/frontend/next-app/Dockerfile
@@ -10,8 +10,8 @@ WORKDIR /app
 # Install dependencies based on the preferred package manager
 COPY package.json package-lock.json* ./
 RUN if [ -f package-lock.json ]; then npm ci; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
 # Rebuild the source code only when needed
 FROM base AS builder
@@ -21,9 +21,10 @@ COPY . .
 
 ENV NEXT_TELEMETRY_DISABLED=1
 
+# Using webpack instead of turbopack because of livekit types conflicts
 RUN if [ -f package-lock.json ]; then npm run build; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
 # Production image, copy all the files and run next
 FROM base AS runner
